channels:
    - anaconda
    - conda-forge
    - defaults
dependencies:
    - python
    - ase
    - pandas
    - pip
    - setuptools
    - matplotlib
    - jupyterlab
    - pip:
        - pyblock
        - datetime
        - jupyterlab_latex
